---


- name: ajout du Master Serveur

  hosts: prodserver1
  remote_user: root

  tasks:


################## INSTALLATION Docker #############################

  - name: Installation des packages
    yum:
      name: "{{ item }}" 
      state: present
    with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

  - name: Set up d'un repository stable
    shell : yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: Installation Docker Engine
    yum:
      name: "{{ item }}" 
      state: present
    with_items:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: démarrage Docker
    service: 
      name: docker
      state: started

################## INSTALLATION Docker #############################

  - name: télécharger le binary et le mettre dans /usr/local/bin
    become: yes
    shell: curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

  - name: Permissions
    become: yes
    shell: chmod +x /usr/local/bin/docker-compose

################## INSTALLATION k8s #############################

#  - name: mise à jour
#    shell: yum update
  

  - name: Installer kubectl
    shell : curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl


  - name: Permissions
    become: yes
    shell : chmod +x ./kubectl

  - name: Copie
    become: yes
    shell : mv ./kubectl /usr/local/bin/kubectl

  - name: Installer minikube
    shell : curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/ 
      
