apiVersion: apps/v1

kind: Deployment
metadata:
  name: app-server
  labels:
    app: app-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-server
  template:
    metadata:
      labels:
        app: app-server
    spec:
      containers:
      - name: app-server
        image: kilokilo8/app:latest
        
        ports:
        - containerPort: 8080

        env:
        - name: MYSQL_ROOT_PASSWORD
           value: password
        - name: MYSQL_USER
           value: julien
        - name: MYSQL_PASSWORD
            value: password
        - name: PMA_HOST
           value: mysql-service
        - name: PMA_PORT
           value: "3306"
